USE ADMINISTRACION_COMPUTADORAS;

-- Creacion de la tabla "PERSONAS_LOG", para almacenar los datos correspondientes
-- DROP TABLE IF EXISTS PERSONAS_LOG;
CREATE TABLE IF NOT EXISTS PERSONAS_LOG (
	id_peronas_log INT PRIMARY KEY AUTO_INCREMENT,
    accion VARCHAR(10) NOT NULL,
    tabla VARCHAR(20) NOT NULL,
    usuario varchar(50) NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL   
) ;

-- Trigger 1: / Tabla: PERSONAS / Tipo: AFTER INSERT
-- Explicacion: registra un log de cada nuevo usuario despues de su alta 
DROP TRIGGER IF EXISTS TGR_LOG_INSERT_PERSONAS;
DELIMITER //
CREATE TRIGGER TGR_LOG_INSERT_PERSONAS 
AFTER INSERT ON ADMINISTRACION_COMPUTADORAS.PERSONAS
FOR EACH ROW
INSERT INTO PERSONAS_LOG 
VALUES ( null,'insert','personas',CURRENT_USER(),CURDATE(),CURTIME());
// DELIMITER ;

-- Trigger 1: / Tabla: PERSONAS / Tipo: BEFORE DELETE
-- Explicacion: registra un log de cada persona antes de ser eliminada
DROP TRIGGER IF EXISTS TGR_LOG_DELETE_PERSONAS;
DELIMITER //
CREATE TRIGGER TGR_LOG_DELETE_PERSONAS
BEFORE DELETE ON ADMINISTRACION_COMPUTADORAS.PERSONAS
FOR EACH ROW
INSERT INTO PERSONAS_LOG 
VALUES (null,'delete','personas',CURRENT_USER(),CURDATE(),CURTIME());
// DELIMITER ;


-- Creacion de la tabla "MOVIMIENTOS_PC", para almacenar los datos correspondientes
-- DROP TABLE IF EXISTS MOVIMIENTOS_PC;
CREATE TABLE IF NOT EXISTS MOVIMIENTOS_PC (
	id_mov_pc INT AUTO_INCREMENT, 
	pc_disponible INT NOT NULL,
    entregada INT NOT NULL,
    tabla VARCHAR(20) NOT NULL,   
	usuario varchar(50) NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    PRIMARY KEY (id_mov_pc)
);

-- Trigger 2: / Tabla: PC_REPARADAS / Tipo: AFTER INSERT
-- Explicacion: registra el valor de 1 por cada PC DESPUES de ser insertada en tabla PC_REPARADAS.
DROP TRIGGER IF EXISTS TGR_PC_DISPONIBLE;
DELIMITER //
CREATE TRIGGER TGR_PC_DISPONIBLE
AFTER INSERT ON PC_REPARADAS
FOR EACH ROW
INSERT INTO MOVIMIENTOS_PC
VALUES (null,1,0,'pc_reparadas',CURRENT_USER(),CURDATE(),CURTIME());
// DELIMITER ;

-- Trigger 2: / Tabla: ENTREGAS / Tipo: BEFORE INSERT
-- Explicacion: registra el valor de 1 por cada PC ANTES de ser insertada en tabla ENTREGAS.
DROP TRIGGER IF EXISTS TGR_PC_ENTREGADAS;
DELIMITER //
CREATE TRIGGER TGR_PC_ENTREGADAS
BEFORE INSERT ON ENTREGAS
FOR EACH ROW
INSERT INTO MOVIMIENTOS_PC
VALUES (null,0,1,'entregadas',CURRENT_USER(),CURDATE(),CURTIME());
// DELIMITER ;
